### PR TITLE
Fixes #8

### LINKED ISSUE #8: Incomplete models for the database.
Complete the model 'Todo' in models.py with the attributes given in the README.md namely
1. create a title attribute -> character field (add a reasonable max length)
2. create a content attribute -> text
3. create a created_at attribute -> timestamp (use imported datetime module)
4. create priority attribute -> integer
5. create priority attribute -> integer
6. In the __str__ function, return the todo object's title

### PR DESCRIPTION
**Pull request by anirudhRowjee**
Hi,
this commit fixes issue #8.

Changelog -
1. Modified `models.py` per requirement.

### CODE REVIEW

**Comment by Varun487** [comment]
Hey, can you change content from a charfield to a textField? Other than that, everything looks great.

**Comment by anirudhRowjee** [comment]
Sure, will do

**Comment by Varun487** [comment]
Great Work! Will merge it. Happy contributing!

**Comment by anirudhRowjee** [comment]
Thank you!

**Comment by Varun487** [comment]
!bounty 100

**Comment by Venkatavaradan-R** [comment]
!bounty 30

**Comment by sakshi2912** [comment]
!bounty 30

**Pull request merged**
