### PR TITLE
Installed Todo app & added paths to todo.urls

### PR DESCRIPTION
**Pull request by tusharrao198**
1. added a Todo app in settings.py file
2. created path of index , add , delete  in 'Todo apps'  urls.py file
3. Added a path to todo.urls for '' and path to todo.urls for 'todo/'url pattern in urls.py

Now app running without any issues.

### CODE REVIEW

**Comment by tusharrao198** [comment]
would be nice to add this repo to `hacktoberfest ` topic  or a `hacktoberfest-accepted `  topic .

**Comment by Varun487** [comment]
Hey, please have a look at [CONTRIBUTING.md](https://github.com/acmpesuecc/Todo_List_In_Django/blob/master/CONTRIBUTING.md) and limit your PR to a specific issue as PRs addressing multiple issues won't be accepted. You could break this into 2 PRs addressing 2 separate issues.

**Comment by tusharrao198** [comment]
ok , I will close this and create 2 new PRs

**Comment by Varun487** [comment]
Cool, thanks

**Pull request closed without merging**
